/**
 * @file application.model.js
 * @description Drizzle schema for the `applications` table.
 *
 * An "application" is a creator's proposal to work on a brand's
 * campaign requirement. It contains an optional pitch message
 * and proposed rate, and tracks status through the review lifecycle.
 *
 * Relationships:
 *   • N → 1  requirements  (the campaign being applied to)
 *   • N → 1  users         (the creator applying)
 */

import { pgTable, uuid, text, integer, timestamp, uniqueIndex } from 'drizzle-orm/pg-core';
import { users } from './user.model.js';
import { requirements } from './requirement.model.js';
import { applicationStatusEnum } from './enums.js';

export const applications = pgTable(
  'applications',
  {
    /** UUID v4 primary key — auto-generated by Postgres */
    id: uuid('id').primaryKey().defaultRandom(),

    /** FK → requirements.id — the campaign this application targets */
    requirementId: uuid('requirement_id')
      .notNull()
      .references(() => requirements.id, { onDelete: 'cascade' }),

    /** FK → users.id — the creator who submitted this application */
    creatorId: uuid('creator_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),

    /** Creator's pitch / cover letter explaining why they're a good fit */
    coverLetter: text('cover_letter'),

    /** Proposed rate in USD (optional — creator's ask) */
    proposedRate: integer('proposed_rate'),

    /** pending | accepted | rejected | withdrawn */
    status: applicationStatusEnum('status').default('pending').notNull(),

    createdAt: timestamp('created_at').defaultNow().notNull(),
    updatedAt: timestamp('updated_at').defaultNow().notNull(),
  },
  (table) => [
    /** A creator can only apply once per requirement */
    uniqueIndex('applications_creator_requirement_idx').on(
      table.creatorId,
      table.requirementId,
    ),
  ],
);
