/**
 * @file message.model.js
 * @description Drizzle schema for the `messages` table.
 *
 * Messages enable communication between brands and creators.
 * A message can optionally reference a specific campaign requirement.
 *
 * Relationships:
 *   • N → 1  users  (sender)
 *   • N → 1  users  (receiver)
 *   • N → 1  requirements  (optional — the campaign context)
 */

import { pgTable, uuid, text, timestamp } from 'drizzle-orm/pg-core';
import { users } from './user.model.js';
import { requirements } from './requirement.model.js';

export const messages = pgTable('messages', {
  /** UUID v4 primary key — auto-generated by Postgres */
  id: uuid('id').primaryKey().defaultRandom(),

  /** FK → users.id — the user who sent the message */
  senderId: uuid('sender_id')
    .notNull()
    .references(() => users.id, { onDelete: 'cascade' }),

  /** FK → users.id — the user receiving the message */
  receiverId: uuid('receiver_id')
    .notNull()
    .references(() => users.id, { onDelete: 'cascade' }),

  /** FK → requirements.id — optional campaign context */
  requirementId: uuid('requirement_id')
    .references(() => requirements.id, { onDelete: 'set null' }),

  /** Message body text */
  content: text('content').notNull(),

  createdAt: timestamp('created_at').defaultNow().notNull(),
});
