// Mock data for Trustfluence platform

export const creators = [
  {
    id: "1",
    name: "Sarah Chen",
    bio: "Lifestyle & beauty content creator sharing authentic product reviews and daily inspiration with my community.",
    platform: "Instagram",
    handle: "@sarahchenlife",
    photo: "https://images.unsplash.com/photo-1758526213838-19d832f4aaa5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx5b3VuZyUyMHdvbWFuJTIwbGlmZXN0eWxlJTIwY3JlYXRvciUyMHBvcnRyYWl0fGVufDF8fHx8MTc3MTU5Mzk3M3ww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    followers: 125000,
    engagementRate: 4.8,
    niches: ["Lifestyle", "Beauty", "Fashion"],
    promotionTypes: ["Sponsored Posts", "Stories", "Reels"],
    rating: 4.7,
    reviewCount: 23,
  },
  {
    id: "2",
    name: "Marcus Rivera",
    bio: "Tech reviewer and gadget enthusiast. I break down complex technology into simple, honest reviews.",
    platform: "YouTube",
    handle: "@marcustech",
    photo: "https://images.unsplash.com/photo-1719257751404-1dea075324bd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcm9mZXNzaW9uYWwlMjBtYW4lMjBjcmVhdGl2ZSUyMGhlYWRzaG90fGVufDF8fHx8MTc3MTU5Mzk3NHww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    followers: 340000,
    engagementRate: 5.2,
    niches: ["Technology", "Gadgets", "Reviews"],
    promotionTypes: ["Video Reviews", "Unboxing", "Tutorials"],
    rating: 4.9,
    reviewCount: 45,
  },
  {
    id: "3",
    name: "Emma Larsson",
    bio: "Fitness coach and wellness advocate. Sharing workouts, nutrition tips, and healthy living content.",
    platform: "Instagram",
    handle: "@emmafit",
    photo: "https://images.unsplash.com/photo-1769636930016-5d9f0ca653aa?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx5b3VuZyUyMGNyZWF0aXZlJTIwcHJvZmVzc2lvbmFsJTIwd29tYW4lMjBoZWFkc2hvdHxlbnwxfHx8fDE3NzE1OTM5NzV8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    followers: 89000,
    engagementRate: 6.1,
    niches: ["Fitness", "Health", "Wellness"],
    promotionTypes: ["Sponsored Posts", "Stories", "Workout Plans"],
    rating: 4.5,
    reviewCount: 18,
  },
  {
    id: "4",
    name: "Alex Kim",
    bio: "Travel photographer and adventure storyteller. Capturing the world one destination at a time.",
    platform: "YouTube",
    handle: "@alexkimtravel",
    photo: "https://images.unsplash.com/photo-1628619487925-e9b8fc4c6b08?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx5b3VuZyUyMG1hbiUyMGNhc3VhbCUyMHBvcnRyYWl0JTIwc21pbGV8ZW58MXx8fHwxNzcxNTAwOTgzfDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    followers: 210000,
    engagementRate: 3.9,
    niches: ["Travel", "Photography", "Adventure"],
    promotionTypes: ["Vlogs", "Sponsored Content", "Brand Trips"],
    rating: 4.6,
    reviewCount: 31,
  },
  {
    id: "5",
    name: "Priya Sharma",
    bio: "Food blogger and recipe developer. Combining traditional recipes with modern cooking techniques.",
    platform: "Instagram",
    handle: "@priyacooks",
    photo: "https://images.unsplash.com/photo-1612237372447-633d5ced1be1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjcmVhdGl2ZSUyMHdvbWFuJTIwcGhvdG9ncmFwaGVyJTIwcG9ydHJhaXR8ZW58MXx8fHwxNzcxNTkzOTc2fDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    followers: 156000,
    engagementRate: 5.5,
    niches: ["Food", "Cooking", "Lifestyle"],
    promotionTypes: ["Recipe Posts", "Stories", "Brand Partnerships"],
    rating: 4.8,
    reviewCount: 27,
  },
  {
    id: "6",
    name: "David Park",
    bio: "Fashion and streetwear content creator. Helping brands connect with the next generation of style.",
    platform: "TikTok",
    handle: "@davidparkstyle",
    photo: "https://images.unsplash.com/photo-1652471943570-f3590a4e52ed?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcm9mZXNzaW9uYWwlMjBoZWFkc2hvdCUyMG1hbiUyMHN1aXR8ZW58MXx8fHwxNzcxNTMyMDA4fDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    followers: 420000,
    engagementRate: 7.3,
    niches: ["Fashion", "Streetwear", "Lifestyle"],
    promotionTypes: ["TikTok Videos", "Hauls", "Try-ons"],
    rating: 4.4,
    reviewCount: 15,
  },
];

export const brands = [
  {
    id: "1",
    name: "NovaTech Solutions",
    logo: "https://images.unsplash.com/photo-1752859951149-7d3fc700a7ec?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0ZWNoJTIwc3RhcnR1cCUyMG9mZmljZSUyMG1vZGVybiUyMHdvcmtzcGFjZXxlbnwxfHx8fDE3NzE1OTM5NzV8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    website: "https://novatech.example.com",
    category: "Technology",
    rating: 4.6,
    trustScore: 92,
    reviewCount: 34,
    description: "Leading tech solutions company focused on innovative consumer electronics and smart home devices.",
  },
  {
    id: "2",
    name: "Velvet & Co",
    logo: "https://images.unsplash.com/photo-1674978037981-fef8cbf2b3a2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmYXNoaW9uJTIwYnJhbmQlMjBsb2dvJTIwbWluaW1hbGlzdHxlbnwxfHx8fDE3NzE1OTM0NzR8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    website: "https://velvetco.example.com",
    category: "Fashion",
    rating: 4.3,
    trustScore: 87,
    reviewCount: 28,
    description: "Premium fashion brand committed to sustainable and ethical clothing production.",
  },
];

export const reviews = [
  {
    id: "1",
    reviewerName: "NovaTech Solutions",
    rating: 5,
    comment: "Sarah delivered exceptional content for our product launch. Her audience engagement was remarkable and the content quality exceeded expectations.",
    date: "2026-02-15",
  },
  {
    id: "2",
    reviewerName: "Velvet & Co",
    rating: 4,
    comment: "Great collaboration! Sarah was professional, creative, and delivered on time. Would definitely work with her again.",
    date: "2026-01-28",
  },
  {
    id: "3",
    reviewerName: "FitPro Supplements",
    rating: 5,
    comment: "Outstanding work ethic and genuine enthusiasm for our brand. Her followers clearly trust her recommendations.",
    date: "2026-01-10",
  },
  {
    id: "4",
    reviewerName: "GreenLeaf Organics",
    rating: 4,
    comment: "Professional and easy to work with. Content was authentic and resonated well with our target audience.",
    date: "2025-12-22",
  },
];

export const brandReviews = [
  {
    id: "1",
    reviewerName: "Sarah Chen",
    rating: 5,
    comment: "NovaTech was an amazing brand to work with. Clear communication, fair compensation, and creative freedom. Highly recommend!",
    date: "2026-02-16",
  },
  {
    id: "2",
    reviewerName: "Marcus Rivera",
    rating: 4,
    comment: "Professional team with well-organized campaigns. They provided all necessary materials on time.",
    date: "2026-01-30",
  },
  {
    id: "3",
    reviewerName: "Emma Larsson",
    rating: 5,
    comment: "One of the best brands I've partnered with. Transparent about expectations and generous with creative direction.",
    date: "2026-01-15",
  },
];

export const requirements = [
  {
    id: "1",
    title: "Summer Product Launch Campaign",
    description: "Looking for lifestyle and beauty creators to promote our new summer skincare collection. We need authentic content showcasing daily usage.",
    brand: "Velvet & Co",
    niches: ["Beauty", "Lifestyle", "Skincare"],
    minFollowers: 50000,
    minEngagement: 3.5,
    budget: "$2,000 - $5,000",
    status: "Open",
  },
  {
    id: "2",
    title: "Tech Review Series",
    description: "Seeking tech reviewers for an in-depth series covering our new smart home product line. Honest, detailed reviews preferred.",
    brand: "NovaTech Solutions",
    niches: ["Technology", "Smart Home", "Reviews"],
    minFollowers: 100000,
    minEngagement: 4.0,
    budget: "$3,000 - $8,000",
    status: "Open",
  },
  {
    id: "3",
    title: "Fitness Challenge Sponsorship",
    description: "Partner with fitness creators for a 30-day fitness challenge featuring our protein supplements and workout gear.",
    brand: "FitPro Supplements",
    niches: ["Fitness", "Health", "Wellness"],
    minFollowers: 30000,
    minEngagement: 5.0,
    budget: "$1,500 - $4,000",
    status: "Open",
  },
  {
    id: "4",
    title: "Holiday Gift Guide Feature",
    description: "Include our products in your holiday gift guide content. Looking for creators across multiple niches.",
    brand: "NovaTech Solutions",
    niches: ["Technology", "Lifestyle", "Gift Ideas"],
    minFollowers: 75000,
    minEngagement: 3.0,
    budget: "$1,000 - $3,000",
    status: "Closed",
  },
  {
    id: "5",
    title: "Street Style Campaign",
    description: "Fashion creators needed for our upcoming streetwear collection launch. Creative freedom encouraged!",
    brand: "Velvet & Co",
    niches: ["Fashion", "Streetwear", "Lifestyle"],
    minFollowers: 40000,
    minEngagement: 4.5,
    budget: "$2,500 - $6,000",
    status: "Open",
  },
];
