/**
 * @file user.model.js
 * @description Drizzle schema for the `users` table.
 *
 * This is the core authentication table. Every person on the platform
 * (creator, brand, or admin) has exactly one row here. Passwords are
 * stored as Argon2 hashes — never in plain text.
 *
 * Relationships:
 *   • 1 → 1  creator_profiles  (if role = 'creator')
 *   • 1 → 1  brand_profiles    (if role = 'brand')
 *   • 1 → N  ratings           (as author or target)
 *   • 1 → N  reviews           (as author or target)
 *   • 1 → N  requirements      (if role = 'brand')
 */

import { pgTable, uuid, varchar, timestamp } from 'drizzle-orm/pg-core';
import { userRoleEnum } from './enums.js';

export const users = pgTable('users', {
  /** UUID v4 primary key — auto-generated by Postgres */
  id: uuid('id').primaryKey().defaultRandom(),

  /** Unique email (lower-cased before insert) */
  email: varchar('email', { length: 255 }).notNull().unique(),

  /** Argon2-hashed password */
  password: varchar('password', { length: 255 }).notNull(),

  /** One of: 'creator' | 'brand' | 'admin' */
  role: userRoleEnum('role').notNull(),

  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
});
